<a href="https://colab.research.google.com/github/Maksym17V2/Machin--learning-bootcamp/blob/main/EkstracjaDanych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import bibliotek

In [1]:

import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.1'

#Załadowanie danych

In [2]:
def fetch_financial_data(company='AMZN'):
    """
    This function fetches stock market quotations.
    """
    import pandas_datareader.data as web
    return web.DataReader(name=company, data_source='stooq')

df_raw = fetch_financial_data()
df_raw.head()

              Open     High      Low   Close    Volume
Date
2026-03-03  203.10  209.178  202.480  208.63  43184918
2026-03-02  204.55  209.730  203.460  208.39  46001010
2026-02-27  206.83  210.330  205.200  210.00  57191213
2026-02-26  210.73  211.050  205.345  207.92  47531800
2026-02-25  210.46  211.590  208.930  210.64  41346400

#Utworzenie kopii danych

In [3]:
df = df_raw.copy()
df = df[:5]
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2026-03-03 to 2026-02-25
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    5 non-null      float64
 1   High    5 non-null      float64
 2   Low     5 non-null      float64
 3   Close   5 non-null      float64
 4   Volume  5 non-null      int64
dtypes: float64(4), int64(1)
memory usage: 240.0 bytes

#Generowanie nowych zmiennych

In [4]:
df.index.month

Index([3, 3, 2, 2, 2], dtype='int32', name='Date')

In [5]:
df['day'] = df.index.day
df['month'] = df.index.month
df['year'] = df.index.year
df

              Open     High      Low   Close    Volume  day  month  year
Date
2026-03-03  203.10  209.178  202.480  208.63  43184918    3      3  2026
2026-03-02  204.55  209.730  203.460  208.39  46001010    2      3  2026
2026-02-27  206.83  210.330  205.200  210.00  57191213   27      2  2026
2026-02-26  210.73  211.050  205.345  207.92  47531800   26      2  2026
2026-02-25  210.46  211.590  208.930  210.64  41346400   25      2  2026

#Dyskretyzacja zmiennej ciągłej

In [6]:
df = pd.DataFrame(data={'height': [175., 178.5, 185., 191., 184.5, 183., 168.]})
df

   height
0   175.0
1   178.5
2   185.0
3   191.0
4   184.5
5   183.0
6   168.0

In [7]:
df['height_cat'] = pd.cut(x=df.height, bins=3)
df

   height          height_cat
0   175.0  (167.977, 175.667]
1   178.5  (175.667, 183.333]
2   185.0    (183.333, 191.0]
3   191.0    (183.333, 191.0]
4   184.5    (183.333, 191.0]
5   183.0  (175.667, 183.333]
6   168.0  (167.977, 175.667]

In [8]:
df['height_cat'] = pd.cut(x=df.height, bins=(160, 175, 180, 195))
df

   height  height_cat
0   175.0  (160, 175]
1   178.5  (175, 180]
2   185.0  (180, 195]
3   191.0  (180, 195]
4   184.5  (180, 195]
5   183.0  (180, 195]
6   168.0  (160, 175]

In [9]:
df['height_cat'] = pd.cut(x=df.height, bins=(160, 175, 180, 195), labels=['small', 'medium', 'high'])
df

   height height_cat
0   175.0      small
1   178.5     medium
2   185.0       high
3   191.0       high
4   184.5       high
5   183.0       high
6   168.0      small

In [10]:
pd.get_dummies(df, drop_first=True, prefix='height')

   height  height_medium  height_high
0   175.0          False        False
1   178.5           True        False
2   185.0          False         True
3   191.0          False         True
4   184.5          False         True
5   183.0          False         True
6   168.0          False        False

#Ekstrakcja cech

In [11]:
df = pd.DataFrame(data={'lang': [['PL', 'ENG'], ['GER', 'ENG', 'PL', 'FRA'], ['RUS']]})
df

                  lang
0            [PL, ENG]
1  [GER, ENG, PL, FRA]
2                [RUS]

In [12]:
df['lang_number'] = df['lang'].apply(len)
df

                  lang  lang_number
0            [PL, ENG]            2
1  [GER, ENG, PL, FRA]            4
2                [RUS]            1

In [13]:
df['PL_flag'] = df['lang'].apply(lambda x: 1 if 'PL' in x else 0)
df

                  lang  lang_number  PL_flag
0            [PL, ENG]            2        1
1  [GER, ENG, PL, FRA]            4        1
2                [RUS]            1        0

In [14]:
df = pd.DataFrame(data={'website': ['wp.pl', 'onet.pl', 'google.com']})
df

      website
0       wp.pl
1     onet.pl
2  google.com

In [15]:
df.website.str.split('.', expand=True)

        0    1
0      wp   pl
1    onet   pl
2  google  com

In [16]:
new = df.website.str.split('.', expand=True)
df['portal'] = new[0]
df['extension'] = new[1]
df

      website  portal extension
0       wp.pl      wp        pl
1     onet.pl    onet        pl
2  google.com  google       com